# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 18:00
from __future__ import unicode_literals

from django.db import migrations

import os

directory = os.path.abspath(os.path.join(os.path.dirname(__file__), '../'))
fp = os.path.join(directory, 'commmittees.csv')

cmd = "BULK INSERT Committees FROM '" + fp + \
      "' WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = " + \
      "'\r\n', ERRORFILE = 'committees.sql.err.csv', TABLOCK);"

def csv2dj_com(apps, schema_editor):
    with open(fp, 'r') as f:
        reader = csv.DictReader(f, delimiter = '|')
        for row in reader:
            obj = Committees(row)
            obj.save()
            print('YAYAYAY')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(csv2dj_com),
        #migrations.RunSQL(cmd)
    ]
